alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: inngest-demo
    match:
      authority:
        exact: ""
      path:
        prefix: /
  - component:
      name: inngest
    match:
      authority:
        exact: ""
      path:
        prefix: /inngest
name: seashell-app
region: nyc
services:
- environment_slug: node-js
  envs:
  - key: INNGEST_SIGNING_KEY
    scope: RUN_AND_BUILD_TIME
    value: signkey-prod-d57942892409d2fb32dd3155a9e41ac7dfeda442a2f48c20505fac1148382912
  - key: INNGEST_EVENT_KEY
    scope: RUN_AND_BUILD_TIME
    value: C80dLv7_xdIlAc-Rka68Mvfd1geJsZ_IWh84vuztkbmkUBcN-VGjN4rh0ocWkuJVEQxoufNst5ESB009YxwbyA
  github:
    branch: main
    repo: zasghar26/inngest-demo
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-d-2vcpu-4gb
  name: inngest-demo
  run_command: npm start
  source_dir: /
- http_port: 8288
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: inngest
    tag: latest
  instance_count: 2
  instance_size_slug: apps-d-2vcpu-4gb
  name: inngest
  run_command: inngest dev
